import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const ResultMarkdown = ({ markdownContent, researchId }) => {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto">
        {/* Paper Container */}
        <div className="bg-white shadow-lg border border-gray-200 min-h-screen">
          <div className="px-12 py-16">
            {/* Research Content */}
            <main className="space-y-8">
              <div className="prose prose-lg max-w-none leading-relaxed">
                <div className="markdown-body text-gray-800 font-serif text-base leading-7">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {markdownContent}
                  </ReactMarkdown>
                </div>
              </div>
            </main>
            {/* Footer */}
            <footer className="mt-16 pt-8 border-t border-gray-300">
              <div className="text-center">
                <div className="text-xs text-gray-500 space-y-2">
                  <p>© AI Co-Researcher</p>
                  <p>Note: This work was generated by AI.</p>

                  <p className="font-mono">Document ID: {researchId}</p>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultMarkdown;
